[package]
name = "battlestar-server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8", features = ["ws"] }
rand = "0.9"
serde = { workspace = true }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tungstenite = "0.28"
