[package]
name = "battlestar-server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
serde = { workspace = true }
serde_json = "1"
supabase_rs = { version = "0.5", features = ["rustls"] }
tokio = { version = "1", features = ["full"] }
tungstenite = "0.28"
